export const actions = {
    ADD_PRODUCT: 'ADD_PRODUCT',
    EDIT_PRODCUT: 'EDIT_PRODUCT',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    SET_INITAL_STORE: 'SET_INITIAL_STORE',
    SET_SELECTED_PRODUCT: 'SET_SELECTED_PRODUCT',
}